"""updated resume model

Revision ID: 0eb0e7b9e28e
Revises: 2d389096c472
Create Date: 2025-05-30 11:37:30.920611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0eb0e7b9e28e'
down_revision: Union[str, None] = '2d389096c472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
status_enum = postgresql.ENUM('SUCCESS', 'FAILURE', 'PENDING', 'NOT_STARTED', name='status')

def upgrade() -> None:
    """Upgrade schema."""
    status_enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('status', sa.Enum('SUCCESS', 'FAILURE', 'PENDING', 'NOT_STARTED', name='status'),
                                       server_default='NOT_STARTED', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'status')
    # ### end Alembic commands ###
    status_enum.drop(op.get_bind())